webtalk_init -webtalk_dir C:/Users/secomd/Documents/UCSC_Schoolwork/Win18/CMPE100/Lab4/Lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 06 15:45:04 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aebbe30c05dd54069fd5011a1f68cb29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e8f3cd4927445719076026b7e673807" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2491 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "43.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18252_KB" -context "xsim\\usage"
webtalk_transmit -clientid 82948536 -regid "" -xml C:/Users/secomd/Documents/UCSC_Schoolwork/Win18/CMPE100/Lab4/Lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/secomd/Documents/UCSC_Schoolwork/Win18/CMPE100/Lab4/Lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/secomd/Documents/UCSC_Schoolwork/Win18/CMPE100/Lab4/Lab4.sim/sim_1/behav/xsim.dir/testTC_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
